### ISSUE TITLE
并不存在 C:\Program Files\Calibre2\app\pylib.zip , 又怎么替换啊?

### ISSUE THREAD

**Issue by kulapati** [snomiao/calibre-utf8-path#1]

**Comment by snomiao** [comment]
据我观察，这个文件在5.0和5.1版本还有，5.2开始没的……
本人对新版本暂无比较好的办法（也许要从头编译也说不定），如果想用这个功能的话可以先装5.1版本
我把安装包一并发到这里了（安装包是官方的）：
[Release pylib.zip for calibre 5.1.0 win32_win64 · snomiao/calibre-utf8-path]( https://github.com/snomiao/calibre-utf8-path/releases/tag/v5.1.0-patch )

**Comment by kulapati** [comment]
谢谢
